### ISSUE TITLE
cool project !

### ISSUE THREAD

**Issue by davephillips** [WIZARDISHUNGRY/vcvrack-rtlsdr#1]
Greetings ! I saw this project and wondered what it's about, so I read up on rtlsdr. I was a ham radio operator when I was a boy (a very long time ago), so I'm excited to read about your work. What's its current status wrt any specific hardware, i.e. can you suggest any particular dongle to buy ? I'm on Linux, btw, if it makes any difference. Anyway, I look forward to the module in Rack, I'll be checking in the project to see (and hopefully hear) how it's going.

**Comment by wizardishungry** [comment]
Hey! I'm just getting audio output working, but I'm having some issues converting from Signed 16 bit PCM audio to VCVRack floats - the audio is mangled. VC tuning is up next. I'm guessing compilation will work on Mac (with correct homebrew packages installed) & Linux.

The vision for the project is to have a voltage controlled tunable AM/FM radio in the VCVRack environment. I'd like to add features such as channel scanning.

I also need to change some of the file mechanisms because it just writes to a random file in `/tmp` (for debugging purposes).

I'm using [this dongle](https://www.amazon.com/dp/B009U7WZCA/), I believe. I originally got it for [dump1090](https://github.com/mutability/dump1090).

While cheap RTL-SDR are cool, you should be aware that the frequency range on many devices is limited to upper frequencies.

Again, I just started working on this a couple hours ago so things are far from having a plugin that you can just download and install.

**Comment by davephillips** [comment]
Thanks for the reply ! I've started looking at dongles and am considering one of the NooElec products, either what you have or the one at https://www.amazon.com/NooElec-NESDR-SMArt-Enclosure-R820T2-Based/dp/B01HA642SW/ref=sr_1_12?. I would like to have the extended range though. Also, I build from source, so I'll be happy to test for you as soon as I get the dongle. Btw, will I need a kernel driver or are these things plug & play devices on Linux ? No rush on replies, I'm an inveterate hub crawler, I'll be watching your project development daily, if not hourly. :) Again, very cool project.

**Comment by wizardishungry** [comment]
No drivers or root privileges needed (think I had to chmod a /dev on OpenBSD once). Libusb makes writing portable usb code really easy.

I don't know a lot about radio, so I'd suggest reading blogs/wikis to see which current dongles/antennas people like. The little cheapo antenna I have is fine for getting started.
